baseURL = "https://blog.wildsky.cc"
languageCode = "zh-tw"
copyright = "<a href=\"https://github.com/wildskyf\">Geng-Zhi Fann</a> &copy; 2017"
theme = "ws"
googleAnalytics = "UA-50389098-1"
title = "ws://blog.wildsky.cc"
enableRobotsTXT = true
hasCJKLanguage = true
log = true
dataDir = "data"
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
summaryLength = 100

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Fedora"
    pre = "<i class='fa fa-heart'></i>"
    weight = 10
    identifier = "fedora"
    url = "/fedora/"
[[menu.main]]
    name = "Subscribe"
    pre = "<i class='fa fa-heart'></i>"
    weight = 5
    identifier = "subscribe"
    url = "/subscribe/"

[author]
name = "wildsky"
email = "wildsky@moztw.org"


[params]
title = "ws://wildsky.cc"
subtitle = "Front-end Developer | Vimer | Firefox Add-on Reviewer | Golang beginner"
author = "Wildsky"

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
enableSocial = true
poweredby = true # Adds powered by hugo and kiss below Copyright

[params.social]
twitter = "wildskyf"
github = "wildskyf"
email = "wildsky@moztw.org"
linkedin = "wildsky"
facebook = "wi1d5ky"
instagram = "wildskyf"

[taxonomies]
category = "categories"
tag = "tags"
