baseURL = "https://blog.wildsky.cc/"
languageCode = "zh-tw"
title = "ws://blog.wildsky.cc"
slogan = "風吹過什麼樣的地方，身上自然而然就會有那樣的氣息。"
theme = "kiss"

[author]
    name = "wildsky"
    email = "wildsky@moztw.org"
